### ISSUE TITLE
Format for proxy file

### ISSUE THREAD

**Issue by pardity** [McGuire00/PollDaddy#1]
What format for the proxy file?

Code:
def get_proxies():
    global meek
    # web proxy request
    text_file = open("proxy.json", "r")
    lines = text_file.readlines()
    meek = [item.replace('\n', '') for item in lines]
    text_file.close()
get_proxies()

**Comment by McGuire00** [comment]
EX:
101.108.136.142:8080
1.0.165.16:8080
1.0.187.80:8213
1.10.189.84:35138
1.0.185.74:8080
1.1.170.177:8080
1.186.242.12:39098
